name: Functional & Integration Testing

# This workflow will automatically run tests on code changes.
on:
  push:
  pull_request:
  workflow_dispatch:

  # Schedule to run automatically every Monday at 12:00 UTC
  schedule:
    - cron: "0 12 * * 1" 

jobs:
  test:
    runs-on: ubuntu-latest

    # Matrix lets GitHub Actions automatically run the tests across multiple Python versions
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make install

      - name: Check required project files
        run: |
          test -f Sleep_health_and_lifestyle_dataset.csv
          test -f analysis_query.ipynb
          test -f Makefile
          test -f Dockerfile
          test -d Testing        
      
      - name: Run linting
        run: make lint

      - name: Run both functional and integration tests with Makefile
        run: make test

      - name: Build Docker image
        run: make docker-build

      - name: Run both functional and integration tests in Docker
        run: make docker-test
